#!/usr/bin/env node

import 'core-js/stable';
import 'regenerator-runtime/runtime';

const launchServer = require('/opt/cncjs/server-cli').default;

launchServer().catch(err => {
  console.error('Error:', err);
});
